import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Head from "next/head"
import Script from "next/script"
import { Noto_Sans_JP } from "next/font/google"

const NotoSansJPFont = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Head>
        <Script src="https://cdn.apple-mapkit.com/mk/5.0.x/mapkit.js"></Script>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${NotoSansJPFont.className} antialiased h-full w-full`}
      >
        {children}
      </body>
    </html>
  )
}
